### PR TITLE
Add basic support for job position

### PR DESCRIPTION
**Pull request by theFox6**
makes vilagers go to a certain position before starting their jobs

### CODE REVIEW

**Comment by sfence** [comment]
I have used property self.in_work in a bad way. That value should be stored somewhere to alive world reload.

What about removing working_villagers world files and use StorageRef returned by minetest.get_mod_storage() instead of it?

**Comment by sfence** [comment]
A have added storage support. It should be easy extendable to store other villagers' values (like home pos, etc).

**Comment by sfence** [comment]
This is now integrated into https://github.com/theFox6/working_villages/pull/19, and the logic is changed (entity static data is used)

**Comment by theFox6** [comment]
There are two things about this solution I want to point out though.
1. So far I have used the luaentity of the villager itself to store data, a persistent storage table is a good idea though, maybe the rest can be migrated to this.
2. I used world files so far because they are kinda debuggable and because I have to de/serialize anyway since deep table structures are used so mod storage is OK, but doesn't make a very big difference.

**Pull request merged**
